// Generated by assets/tools/build_hardscapes.mjs; coordinates use each SVG viewBox.
export const expandedHardscapeSurfaces = {
  "classic": [
    {
      "x": 58.78,
      "y": 160.2,
      "width": 36.11,
      "angle": -31.14,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-0"
    },
    {
      "x": 92.23,
      "y": 219.13,
      "width": 16.7,
      "angle": -80.64,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-1"
    },
    {
      "x": 139.54,
      "y": 215.25,
      "width": 14.67,
      "angle": -76.48,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-2"
    },
    {
      "x": 176.33,
      "y": 225.89,
      "width": 10.55,
      "angle": -73.64,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-3"
    },
    {
      "x": 231.44,
      "y": 220.76,
      "width": 11.1,
      "angle": -73.35,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-4"
    },
    {
      "x": 274.17,
      "y": 215.41,
      "width": 12.19,
      "angle": -70.74,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-5"
    },
    {
      "x": 307.85,
      "y": 168.26,
      "width": 24.61,
      "angle": -34.04,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-6"
    },
    {
      "x": 354.46,
      "y": 213.23,
      "width": 15.55,
      "angle": -70.98,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-7"
    },
    {
      "x": 407.47,
      "y": 222.34,
      "width": 12.84,
      "angle": -71,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-8"
    },
    {
      "x": 52.97,
      "y": 231.11,
      "width": 8.93,
      "angle": -81.61,
      "material": "wood",
      "layer": "middle",
      "piece": "middle-wood-9"
    },
    {
      "x": 142.31,
      "y": 200.05,
      "width": 39.01,
      "angle": -22.55,
      "material": "stone",
      "layer": "middle",
      "piece": "middle-rock-10"
    },
    {
      "x": 234.28,
      "y": 223.77,
      "width": 13.44,
      "angle": -86.31,
      "material": "wood",
      "layer": "middle",
      "piece": "middle-wood-11"
    },
    {
      "x": 316.65,
      "y": 217.48,
      "width": 15.6,
      "angle": -81.15,
      "material": "wood",
      "layer": "middle",
      "piece": "middle-wood-12"
    },
    {
      "x": 382.06,
      "y": 211.25,
      "width": 13.51,
      "angle": -72.8,
      "material": "wood",
      "layer": "middle",
      "piece": "middle-wood-13"
    },
    {
      "x": 49.74,
      "y": 243.63,
      "width": 15,
      "angle": 3.95,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-14"
    },
    {
      "x": 137.44,
      "y": 238.91,
      "width": 18.36,
      "angle": 1.06,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-15"
    },
    {
      "x": 191.38,
      "y": 236.28,
      "width": 8.98,
      "angle": -39.06,
      "material": "stone",
      "layer": "foreground",
      "piece": "foreground-rock-16"
    },
    {
      "x": 253.41,
      "y": 240.1,
      "width": 25.56,
      "angle": 3.53,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-17"
    },
    {
      "x": 311.58,
      "y": 241.56,
      "width": 15.78,
      "angle": 2.68,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-18"
    },
    {
      "x": 413.59,
      "y": 243.13,
      "width": 27.71,
      "angle": 0.28,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-19"
    }
  ],
  "stone-ridge": [
    {
      "x": 84.58,
      "y": 310.47,
      "width": 96.44,
      "angle": -26.06,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-0"
    },
    {
      "x": 170.02,
      "y": 418.39,
      "width": 23.67,
      "angle": -86.66,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-1"
    },
    {
      "x": 258.33,
      "y": 323.3,
      "width": 91.21,
      "angle": -29.41,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-2"
    },
    {
      "x": 335.23,
      "y": 360.52,
      "width": 91.82,
      "angle": -23.87,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-3"
    },
    {
      "x": 401.32,
      "y": 318.57,
      "width": 57.36,
      "angle": -37.56,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-4"
    },
    {
      "x": 461.55,
      "y": 443.73,
      "width": 28.05,
      "angle": -72.92,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-5"
    },
    {
      "x": 544.6,
      "y": 337.13,
      "width": 67.64,
      "angle": -37.6,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-6"
    },
    {
      "x": 599.58,
      "y": 420.63,
      "width": 21.93,
      "angle": -69.29,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-7"
    },
    {
      "x": 676.81,
      "y": 409.43,
      "width": 34.78,
      "angle": -71.83,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-8"
    },
    {
      "x": 776.61,
      "y": 331.41,
      "width": 69.91,
      "angle": -17.16,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-9"
    },
    {
      "x": 819.05,
      "y": 326.35,
      "width": 69.75,
      "angle": -29.46,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-10"
    },
    {
      "x": 896.41,
      "y": 333.01,
      "width": 105.02,
      "angle": -26.29,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-11"
    },
    {
      "x": 90.08,
      "y": 369.07,
      "width": 95.16,
      "angle": -32.95,
      "material": "stone",
      "layer": "middle",
      "piece": "middle-rock-12"
    },
    {
      "x": 261.17,
      "y": 460.33,
      "width": 30.28,
      "angle": -85.91,
      "material": "wood",
      "layer": "middle",
      "piece": "middle-wood-13"
    },
    {
      "x": 439.03,
      "y": 404.18,
      "width": 49.78,
      "angle": -22.12,
      "material": "stone",
      "layer": "middle",
      "piece": "middle-rock-14"
    },
    {
      "x": 547.96,
      "y": 449.25,
      "width": 35.81,
      "angle": -81.35,
      "material": "wood",
      "layer": "middle",
      "piece": "middle-wood-15"
    },
    {
      "x": 706.34,
      "y": 367.49,
      "width": 86.47,
      "angle": -39.3,
      "material": "stone",
      "layer": "middle",
      "piece": "middle-rock-16"
    },
    {
      "x": 886.91,
      "y": 399.92,
      "width": 55.36,
      "angle": -17.68,
      "material": "stone",
      "layer": "middle",
      "piece": "middle-rock-17"
    },
    {
      "x": 134.89,
      "y": 471.11,
      "width": 20.86,
      "angle": -34.87,
      "material": "stone",
      "layer": "foreground",
      "piece": "foreground-rock-18"
    },
    {
      "x": 206.09,
      "y": 476.01,
      "width": 22.67,
      "angle": -35.81,
      "material": "stone",
      "layer": "foreground",
      "piece": "foreground-rock-19"
    },
    {
      "x": 346.17,
      "y": 473.92,
      "width": 42.76,
      "angle": -3.51,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-20"
    },
    {
      "x": 464.74,
      "y": 473.98,
      "width": 47.75,
      "angle": -4.62,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-21"
    },
    {
      "x": 548.2,
      "y": 467.87,
      "width": 27.21,
      "angle": -43.25,
      "material": "stone",
      "layer": "foreground",
      "piece": "foreground-rock-22"
    },
    {
      "x": 643.82,
      "y": 470.95,
      "width": 28.64,
      "angle": -25.82,
      "material": "stone",
      "layer": "foreground",
      "piece": "foreground-rock-23"
    },
    {
      "x": 784.52,
      "y": 468.3,
      "width": 24.02,
      "angle": -15.4,
      "material": "stone",
      "layer": "foreground",
      "piece": "foreground-rock-24"
    },
    {
      "x": 866.27,
      "y": 467.33,
      "width": 23.77,
      "angle": -16.24,
      "material": "stone",
      "layer": "foreground",
      "piece": "foreground-rock-25"
    }
  ],
  "fallen-timber": [
    {
      "x": 87.58,
      "y": 320.77,
      "width": 77.58,
      "angle": -15.99,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-0"
    },
    {
      "x": 179.45,
      "y": 440.35,
      "width": 35.89,
      "angle": -79.19,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-1"
    },
    {
      "x": 276.01,
      "y": 428.09,
      "width": 27.16,
      "angle": -73.01,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-2"
    },
    {
      "x": 366.2,
      "y": 416.67,
      "width": 28.6,
      "angle": -74.15,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-3"
    },
    {
      "x": 470.73,
      "y": 443.24,
      "width": 38.68,
      "angle": -77.95,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-4"
    },
    {
      "x": 562.02,
      "y": 443.69,
      "width": 31.03,
      "angle": -76.43,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-5"
    },
    {
      "x": 629.41,
      "y": 367.82,
      "width": 56.32,
      "angle": -40.12,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-6"
    },
    {
      "x": 728.21,
      "y": 442.58,
      "width": 24.38,
      "angle": -76.51,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-7"
    },
    {
      "x": 796.53,
      "y": 417.88,
      "width": 27.08,
      "angle": -82.49,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-8"
    },
    {
      "x": 902.71,
      "y": 421.78,
      "width": 38.31,
      "angle": -79.62,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-9"
    },
    {
      "x": 135.61,
      "y": 403.6,
      "width": 87.24,
      "angle": -21.83,
      "material": "stone",
      "layer": "middle",
      "piece": "middle-rock-10"
    },
    {
      "x": 366.1,
      "y": 433.08,
      "width": 36.9,
      "angle": -82.22,
      "material": "wood",
      "layer": "middle",
      "piece": "middle-wood-11"
    },
    {
      "x": 498.47,
      "y": 404.65,
      "width": 56.92,
      "angle": -28.39,
      "material": "stone",
      "layer": "middle",
      "piece": "middle-rock-12"
    },
    {
      "x": 687.33,
      "y": 447.33,
      "width": 38.02,
      "angle": -75.66,
      "material": "wood",
      "layer": "middle",
      "piece": "middle-wood-13"
    },
    {
      "x": 808.64,
      "y": 382.51,
      "width": 59.38,
      "angle": -26.49,
      "material": "stone",
      "layer": "middle",
      "piece": "middle-rock-14"
    },
    {
      "x": 76.65,
      "y": 485.97,
      "width": 28.04,
      "angle": -2.61,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-15"
    },
    {
      "x": 228.31,
      "y": 475.82,
      "width": 16.59,
      "angle": -44.19,
      "material": "stone",
      "layer": "foreground",
      "piece": "foreground-rock-16"
    },
    {
      "x": 380.81,
      "y": 482.45,
      "width": 45.13,
      "angle": -4.07,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-17"
    },
    {
      "x": 466.72,
      "y": 474.18,
      "width": 32.09,
      "angle": -5.31,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-18"
    },
    {
      "x": 658.6,
      "y": 480.24,
      "width": 56.94,
      "angle": -3.68,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-19"
    },
    {
      "x": 719.03,
      "y": 480.77,
      "width": 44.38,
      "angle": 3.74,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-20"
    },
    {
      "x": 922.88,
      "y": 482.42,
      "width": 65.99,
      "angle": -4.47,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-21"
    }
  ],
  "woodland-pillars": [
    {
      "x": 91.22,
      "y": 328.94,
      "width": 94.45,
      "angle": -35.79,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-0"
    },
    {
      "x": 134.53,
      "y": 416.94,
      "width": 39.45,
      "angle": -77.79,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-1"
    },
    {
      "x": 212.69,
      "y": 333.79,
      "width": 58.26,
      "angle": -25.31,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-2"
    },
    {
      "x": 269.52,
      "y": 361.33,
      "width": 83.84,
      "angle": -42.93,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-3"
    },
    {
      "x": 314.39,
      "y": 412.51,
      "width": 35.61,
      "angle": -71.55,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-4"
    },
    {
      "x": 397.05,
      "y": 324.41,
      "width": 84.12,
      "angle": -40.27,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-5"
    },
    {
      "x": 441.58,
      "y": 358.08,
      "width": 89.48,
      "angle": -21.93,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-6"
    },
    {
      "x": 492.36,
      "y": 365.55,
      "width": 65.45,
      "angle": -36,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-7"
    },
    {
      "x": 572.19,
      "y": 423.4,
      "width": 36.48,
      "angle": -84.46,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-8"
    },
    {
      "x": 619.28,
      "y": 342.25,
      "width": 65.35,
      "angle": -43.47,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-9"
    },
    {
      "x": 679.98,
      "y": 321.48,
      "width": 92.31,
      "angle": -35.73,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-10"
    },
    {
      "x": 751.41,
      "y": 415.07,
      "width": 39.41,
      "angle": -75.38,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-11"
    },
    {
      "x": 820.1,
      "y": 364.21,
      "width": 76.72,
      "angle": -20.38,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-12"
    },
    {
      "x": 843.92,
      "y": 433.87,
      "width": 17.99,
      "angle": -81.38,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-13"
    },
    {
      "x": 905.36,
      "y": 429.88,
      "width": 38.48,
      "angle": -79.74,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-14"
    },
    {
      "x": 104.38,
      "y": 397.55,
      "width": 66.16,
      "angle": -34.38,
      "material": "stone",
      "layer": "middle",
      "piece": "middle-rock-15"
    },
    {
      "x": 217.12,
      "y": 429.85,
      "width": 26.54,
      "angle": -79.78,
      "material": "wood",
      "layer": "middle",
      "piece": "middle-wood-16"
    },
    {
      "x": 347.26,
      "y": 441.67,
      "width": 35.19,
      "angle": -86.42,
      "material": "wood",
      "layer": "middle",
      "piece": "middle-wood-17"
    },
    {
      "x": 455.96,
      "y": 433.94,
      "width": 20.22,
      "angle": -69.85,
      "material": "wood",
      "layer": "middle",
      "piece": "middle-wood-18"
    },
    {
      "x": 555.82,
      "y": 383.89,
      "width": 61.78,
      "angle": -24.01,
      "material": "stone",
      "layer": "middle",
      "piece": "middle-rock-19"
    },
    {
      "x": 646.06,
      "y": 460.77,
      "width": 24.2,
      "angle": -71.87,
      "material": "wood",
      "layer": "middle",
      "piece": "middle-wood-20"
    },
    {
      "x": 792.08,
      "y": 423.07,
      "width": 34.79,
      "angle": -82.11,
      "material": "wood",
      "layer": "middle",
      "piece": "middle-wood-21"
    },
    {
      "x": 889.62,
      "y": 386.08,
      "width": 84.21,
      "angle": -18.97,
      "material": "stone",
      "layer": "middle",
      "piece": "middle-rock-22"
    },
    {
      "x": 80.72,
      "y": 482.06,
      "width": 38.44,
      "angle": -4.75,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-23"
    },
    {
      "x": 204.42,
      "y": 484.66,
      "width": 61.53,
      "angle": 0.09,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-24"
    },
    {
      "x": 328.77,
      "y": 475.67,
      "width": 42.38,
      "angle": 5.18,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-25"
    },
    {
      "x": 390.67,
      "y": 474.72,
      "width": 64.69,
      "angle": 3.71,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-26"
    },
    {
      "x": 481.69,
      "y": 479.14,
      "width": 48.64,
      "angle": 1.95,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-27"
    },
    {
      "x": 598.15,
      "y": 471.33,
      "width": 47.18,
      "angle": 3.17,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-28"
    },
    {
      "x": 699.38,
      "y": 477.51,
      "width": 35.17,
      "angle": -2.18,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-29"
    },
    {
      "x": 778.29,
      "y": 484.01,
      "width": 50.9,
      "angle": -1.48,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-30"
    },
    {
      "x": 879.43,
      "y": 474.32,
      "width": 16.45,
      "angle": -23.82,
      "material": "stone",
      "layer": "foreground",
      "piece": "foreground-rock-31"
    }
  ],
  "branching-banks": [
    {
      "x": 91.88,
      "y": 323.26,
      "width": 70.58,
      "angle": -21.84,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-0"
    },
    {
      "x": 137.14,
      "y": 433.66,
      "width": 39.28,
      "angle": -81.42,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-1"
    },
    {
      "x": 190.48,
      "y": 339.59,
      "width": 58.84,
      "angle": -15.55,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-2"
    },
    {
      "x": 214.62,
      "y": 324.74,
      "width": 71.75,
      "angle": -41.86,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-3"
    },
    {
      "x": 270.29,
      "y": 444.55,
      "width": 21.87,
      "angle": -80.24,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-4"
    },
    {
      "x": 339.85,
      "y": 430.43,
      "width": 36.75,
      "angle": -78.82,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-5"
    },
    {
      "x": 368.1,
      "y": 410.14,
      "width": 19.25,
      "angle": -84.31,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-6"
    },
    {
      "x": 423.74,
      "y": 339.89,
      "width": 64.17,
      "angle": -33.39,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-7"
    },
    {
      "x": 472.85,
      "y": 439.18,
      "width": 18.78,
      "angle": -70.64,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-8"
    },
    {
      "x": 541.2,
      "y": 332.77,
      "width": 105.54,
      "angle": -32.12,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-9"
    },
    {
      "x": 567.1,
      "y": 428.93,
      "width": 31.91,
      "angle": -84.57,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-10"
    },
    {
      "x": 613.06,
      "y": 328.22,
      "width": 62.42,
      "angle": -21.27,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-11"
    },
    {
      "x": 665.6,
      "y": 409.9,
      "width": 39.74,
      "angle": -73.29,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-12"
    },
    {
      "x": 710.41,
      "y": 425.56,
      "width": 34.08,
      "angle": -73.52,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-13"
    },
    {
      "x": 761.87,
      "y": 416,
      "width": 25.68,
      "angle": -78.4,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-14"
    },
    {
      "x": 823.62,
      "y": 372.67,
      "width": 78.6,
      "angle": -38.45,
      "material": "stone",
      "layer": "background",
      "piece": "rear-rock-15"
    },
    {
      "x": 871.71,
      "y": 413.77,
      "width": 19.7,
      "angle": -71.14,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-16"
    },
    {
      "x": 936,
      "y": 419.96,
      "width": 21.26,
      "angle": -86.38,
      "material": "wood",
      "layer": "background",
      "piece": "rear-wood-17"
    },
    {
      "x": 82.27,
      "y": 382.79,
      "width": 69.55,
      "angle": -27.78,
      "material": "stone",
      "layer": "middle",
      "piece": "middle-rock-18"
    },
    {
      "x": 170.17,
      "y": 383.14,
      "width": 70.01,
      "angle": -24.3,
      "material": "stone",
      "layer": "middle",
      "piece": "middle-rock-19"
    },
    {
      "x": 301.14,
      "y": 448.47,
      "width": 22.46,
      "angle": -84.35,
      "material": "wood",
      "layer": "middle",
      "piece": "middle-wood-20"
    },
    {
      "x": 389.18,
      "y": 383.27,
      "width": 79.38,
      "angle": -37.96,
      "material": "stone",
      "layer": "middle",
      "piece": "middle-rock-21"
    },
    {
      "x": 447.42,
      "y": 462.47,
      "width": 22.01,
      "angle": -85.72,
      "material": "wood",
      "layer": "middle",
      "piece": "middle-wood-22"
    },
    {
      "x": 522.37,
      "y": 441.36,
      "width": 22.2,
      "angle": -79.64,
      "material": "wood",
      "layer": "middle",
      "piece": "middle-wood-23"
    },
    {
      "x": 611.26,
      "y": 437.45,
      "width": 27.11,
      "angle": -86.07,
      "material": "wood",
      "layer": "middle",
      "piece": "middle-wood-24"
    },
    {
      "x": 701.15,
      "y": 430.51,
      "width": 35.58,
      "angle": -84.33,
      "material": "wood",
      "layer": "middle",
      "piece": "middle-wood-25"
    },
    {
      "x": 805.97,
      "y": 402.73,
      "width": 66.92,
      "angle": -35.52,
      "material": "stone",
      "layer": "middle",
      "piece": "middle-rock-26"
    },
    {
      "x": 892.88,
      "y": 424.18,
      "width": 59.09,
      "angle": -22.05,
      "material": "stone",
      "layer": "middle",
      "piece": "middle-rock-27"
    },
    {
      "x": 80.87,
      "y": 482.37,
      "width": 44.68,
      "angle": 3.66,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-28"
    },
    {
      "x": 145.28,
      "y": 478.24,
      "width": 62.39,
      "angle": 3.09,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-29"
    },
    {
      "x": 245.37,
      "y": 474.42,
      "width": 61.78,
      "angle": -3.79,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-30"
    },
    {
      "x": 313.23,
      "y": 481.71,
      "width": 33.27,
      "angle": 3.28,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-31"
    },
    {
      "x": 394.23,
      "y": 483.26,
      "width": 60.23,
      "angle": 1.41,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-32"
    },
    {
      "x": 452.94,
      "y": 470.43,
      "width": 30.79,
      "angle": -26.01,
      "material": "stone",
      "layer": "foreground",
      "piece": "foreground-rock-33"
    },
    {
      "x": 542.11,
      "y": 485.06,
      "width": 35.31,
      "angle": -1.75,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-34"
    },
    {
      "x": 602.54,
      "y": 466.04,
      "width": 28.32,
      "angle": -27.15,
      "material": "stone",
      "layer": "foreground",
      "piece": "foreground-rock-35"
    },
    {
      "x": 708.99,
      "y": 482.99,
      "width": 61.26,
      "angle": -1.52,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-36"
    },
    {
      "x": 749.97,
      "y": 466.11,
      "width": 27.37,
      "angle": -40.02,
      "material": "stone",
      "layer": "foreground",
      "piece": "foreground-rock-37"
    },
    {
      "x": 841.58,
      "y": 484.98,
      "width": 42.31,
      "angle": 3.75,
      "material": "wood",
      "layer": "foreground",
      "piece": "foreground-wood-38"
    },
    {
      "x": 905.67,
      "y": 473.65,
      "width": 26.91,
      "angle": -24.42,
      "material": "stone",
      "layer": "foreground",
      "piece": "foreground-rock-39"
    }
  ]
}
