import { useState } from 'react'
import Dialog from './Dialog'
import Icon from './Icon'
import RoomScene from './RoomScene'
import { HealthStats, SpeciesPanel, TankWarnings } from './Pages'
import { FISH_DETAILS, FILTERS, GLASS, SANDS, SIZES, createTank, simulate, tankCost } from '../lib/tank'
import { CHECK_IN_REWARD, SUPPLIES } from '../lib/workspace'

export function NewTankDialog({ coins, onCreate, onClose }) {
  const [name, setName] = useState('A new little world')
  const [size, setSize] = useState('60p')
  const [glass, setGlass] = useState('regular')
  const tank = { ...createTank(), name: name.trim() || 'A new little world', size, glass, fish: {}, plants: {} }
  const cost = tankCost(tank)
  return <Dialog title="Make room for a new world." className="new-tank-dialog" onClose={onClose}><p className="dialog-intro">One room, three sizes. Start with an empty tank, a substrate and a sponge filter.</p><RoomScene tank={tank} compact /><form onSubmit={event => { event.preventDefault(); onCreate(tank) }}><label className="form-label" htmlFor="new-tank-name">Give your tank a name</label><input id="new-tank-name" className="form-input" maxLength={40} value={name} onChange={event => setName(event.target.value)} /><fieldset className="size-fieldset"><legend>Please select a fish tank size</legend><div>{SIZES.map(item => <button type="button" key={item.id} aria-pressed={size === item.id} onClick={() => setSize(item.id)}><strong>{item.name}</strong><span>{item.litres} L</span><small>{item.dimensions}</small></button>)}</div></fieldset><label className="form-label" htmlFor="new-glass">Glass finish</label><select id="new-glass" className="form-input" value={glass} onChange={event => setGlass(event.target.value)}>{GLASS.map(item => <option key={item.id} value={item.id}>{item.name} {item.price ? `· +${item.price} coins` : '· included'}</option>)}</select><div className="create-cost"><span>Tank + substrate + filter<strong>{cost} coins</strong></span><small>{coins} coins available</small></div><button className="primary-button dialog-cta" type="submit" disabled={cost > coins}>Create my tank <Icon name="plus" size={16} /></button>{cost > coins && <p className="inline-help">Collect a daily check-in or care reward to make room for this tank.</p>}</form></Dialog>
}

export function SetupDialog({ tank, onSetup, onClose }) {
  return <Dialog title="The little details." onClose={onClose}><p className="dialog-intro">Change this tank’s setup. Upgrades use the difference in coin prices; trade-ins refund it.</p><div className="setup-fields">{[['size', 'Tank size', SIZES], ['glass', 'Glass finish', GLASS], ['sand', 'Substrate', SANDS], ['filter', 'Filtration', FILTERS]].map(([field, title, options]) => <div key={field}><label className="form-label" htmlFor={`setup-${field}`}>{title}</label><select className="form-input" id={`setup-${field}`} value={tank[field] || 'regular'} onChange={event => onSetup(field, event.target.value)}>{options.map(item => <option key={item.id} value={item.id}>{item.name} · {item.price} coins</option>)}</select></div>)}</div><button className="primary-button dialog-cta" onClick={onClose}>Back to my tank <Icon name="arrow" size={16} /></button></Dialog>
}

export function CheckInDialog({ workspace, checkedIn, onClaim, onClose }) {
  return <Dialog title={checkedIn ? 'A little hello, collected.' : 'Good to see you again.'} onClose={onClose}><div className="checkin-illustration"><Icon name="calendar" size={56} /><span>+{CHECK_IN_REWARD}</span><small>coins for today’s little hello</small></div><p className="dialog-intro centered">Come back for a little calm. Your check-in adds {CHECK_IN_REWARD} coins to the balance shared by all your tanks.</p><div className="streak-row"><span>Current streak</span><strong>{workspace.checkIn.streak} {workspace.checkIn.streak === 1 ? 'day' : 'days'}</strong></div><button className="primary-button dialog-cta" disabled={checkedIn} onClick={onClaim}>{checkedIn ? 'Collected today' : `Collect ${CHECK_IN_REWARD} coins`}<Icon name={checkedIn ? 'check' : 'plus'} size={17} /></button><p className="inline-help">Available once each day, using this browser’s local date.</p></Dialog>
}

export function ResourcesDialog({ workspace, onClose }) {
  const quantities = ['fish', 'plants'].map(type => ({ type, count: workspace.tanks.reduce((sum, tank) => sum + Object.values(tank[type]).reduce((total, n) => total + n, 0), 0) }))
  return <Dialog title="Your little bag of possibilities." onClose={onClose}><p className="dialog-intro">One bag for all your tanks. Stock up in Fish store, then use a little at a time.</p><div className="bag-balance"><span className="coin-symbol">✦</span><strong>{workspace.coins}</strong><span>coins available</span></div><div className="bag-list">{SUPPLIES.map(item => <div key={item.id}><span className={`care-icon ${item.id === 'food' ? 'peach' : item.id === 'water' ? 'blue' : 'green'}`}><Icon name={item.icon} size={22} /></span><span>{item.name}<small>Shared care supply</small></span><strong>{workspace.resources[item.id]}<small>{item.unit}</small></strong></div>)}</div><div className="bag-equipped"><h3>Already at home</h3><p>{workspace.tanks.length} tanks · {quantities[0].count} fish · {quantities[1].count} plants</p><small>Purchased fish, plants and equipment are installed in your tanks.</small></div><a className="primary-button dialog-cta" href="#/store" onClick={onClose}>Visit Fish store <Icon name="arrow" size={16} /></a></Dialog>
}

export function TankDetailDialog({ tank, onObserve, onCopy, onClose }) {
  return <Dialog title={tank.name} className="tank-detail-dialog" onClose={onClose}><p className="dialog-intro">{tank.owner === 'You' ? 'Your local gallery tank.' : `${tank.owner || 'A fellow creator'}’s aquarium · a read-only example.`}</p><div className="tank-detail-observe"><button className="secondary-button" onClick={() => onObserve(tank)}><Icon name="search" size={15} />Observe tank</button></div><RoomScene tank={tank} compact /><HealthStats tank={tank} /><TankWarnings tank={tank} /><div className="detail-species"><SpeciesPanel tank={tank} readOnly /><div className="detail-setup"><h3>A peek at the setup</h3><dl><div><dt>Tank</dt><dd>{tank.size.toUpperCase()} · {SIZES.find(item => item.id === tank.size).litres} L</dd></div><div><dt>Substrate</dt><dd>{SANDS.find(item => item.id === tank.sand).name}</dd></div><div><dt>Filter</dt><dd>{FILTERS.find(item => item.id === tank.filter).name}</dd></div><div><dt>Water balance</dt><dd>{getDemoQuality(tank)}%</dd></div></dl></div></div><button className="primary-button dialog-cta" onClick={() => onCopy(tank)}>Make my own copy · {tankCost(tank)} coins <Icon name="plus" size={16} /></button><p className="inline-help">Creates a new tank in your collection. Your existing tanks stay saved.</p></Dialog>
}

function getDemoQuality(tank) { return simulate(tank).quality }

export function SpeciesDialog({ item, onAdd, onClose }) {
  const details = FISH_DETAILS[item.id]
  return <Dialog title={item.name} onClose={onClose}><div className={`species-hero ${item.photo ? 'species-hero-photo' : ''} ${item.photoFit === 'contain' ? 'species-hero-contain' : ''}`} style={{ '--item-color': item.color }}><img src={item.photo || item.art} alt={item.name} onError={event => { event.currentTarget.onerror = null; event.currentTarget.src = item.art }} />{item.photoCredit && <span className="species-photo-credit">Photo: <a href={item.photoSource} target="_blank" rel="noreferrer">{item.photoCredit}</a>{item.photoLicense && <> · <a href={item.photoLicenseUrl} target="_blank" rel="noreferrer">{item.photoLicense}</a></>}</span>}</div>{item.scientific && <p className="scientific-name">{item.scientific}</p>}<p className="dialog-intro">{item.description}</p>{details && <dl className="species-facts">{[['Temperament', details.temperament], ['Food needs', details.diet], ['Space', details.space], ['Waste load', details.waste]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>}<button className="primary-button dialog-cta" onClick={() => onAdd(item.type, item.id)}>Add to my tank · {item.price} coins <Icon name="plus" size={16} /></button><a className="encyclopedia-dialog-link text-link" href={`#/learn?entry=${item.type === 'fish' ? 'fish' : 'plant'}-${item.id}`} onClick={onClose}>Read the full encyclopedia entry <Icon name="arrow" size={15} /></a></Dialog>
}

export function PreviewDialog({ tank, onClose }) {
  const result = simulate(tank)
  return <Dialog title="A little look into the future." onClose={onClose}><div className="preview-scene"><RoomScene tank={tank} compact /><span>DAY 30</span></div><h3 className="preview-outlook">{result.outlook}</h3><div className="preview-results"><div><span>Water balance</span><strong>{result.quality}%</strong></div><div><span>Your greenery</span><strong>{result.growth}</strong></div><div><span>Room to breathe</span><strong>{result.load > result.capacity ? 'Needs more room' : 'Comfortable'}</strong></div></div><p className="preview-explanation">{result.warnings.length ? result.warnings.join(' ') : 'Your plants and filter have enough capacity for this demo setup. Keep up the small daily care.'}</p><p className="inline-help">A simplified estimate assuming regular care. Previewing does not change your saved tank.</p><button className="primary-button dialog-cta" onClick={onClose}>Back to my tank <Icon name="arrow" size={16} /></button></Dialog>
}

export function GuideDialog({ onClose }) {
  return <Dialog title="A small world. A simple start." onClose={onClose}><p className="dialog-intro">You don’t need to know everything about fishkeeping. Start with a little curiosity.</p><ol className="help-steps"><li><span>01</span><div><h3>Your room, your tanks</h3><p>Switch between your tanks in My tanks. Use the furniture to compare aquarium sizes.</p></div></li><li><span>02</span><div><h3>Find a little inspiration</h3><p>Explore Tank idea. Open a setup to see its swimmers, plants and water status.</p></div></li><li><span>03</span><div><h3>Shop, care and learn</h3><p>Choose a tank in Fish store. Check in for coins, buy supplies and learn about your fish.</p></div></li></ol><div className="dialog-note"><Icon name="info" size={18} /><p>This demo saves in this browser. Shared links show snapshots. Accounts, cross-device saving and live public tanks will come with a cloud backend.</p></div><button className="primary-button dialog-cta" onClick={onClose}>Let’s make something <Icon name="arrow" size={16} /></button></Dialog>
}
